<template>
  <AppModalShell
    :open="open"
    :title="port?.title || $t('brain.browserTitle')"
    size="lg"
    body-compact
    @close="$emit('close')"
  >
    <section v-if="port" class="brain-unit-browser">
      <div class="brain-unit-browser__meta">
        <span>{{ domainLabel }}</span>
        <span v-if="port.sourcePath">{{ port.sourcePath }}</span>
        <span v-if="port.recallableInChat">{{ $t('brain.meta.recallable') }}</span>
        <span v-else>{{ $t('brain.meta.notRecallable') }}</span>
        <span v-if="port.writableByAI">{{ $t('brain.meta.writableDraft') }}</span>
      </div>

      <RecallCompilePagePanel
        v-if="port.hasCompilePage && compilePage"
        :model-value="compilePage"
        :title="$t('brain.compilePageTitle')"
        :editable="false"
        :relation-hints-editable="false"
      />

      <section v-if="port.pendingVersion" class="brain-unit-browser__versions">
        <header class="brain-unit-browser__pending-header">
          <div>
            <strong>{{ port.pendingVersion.mode === 'update' ? $t('brain.pending.updateTitle') : $t('brain.pending.createTitle') }}</strong>
            <span>{{ port.pendingVersion.reason || $t('brain.pending.autoGeneratedReason') }}</span>
          </div>
          <div class="brain-unit-browser__pending-actions">
            <button type="button" @click="$emit('edit-pending')">{{ $t('common.edit') }}</button>
            <button type="button" @click="$emit('reject-pending')">{{ $t('brain.pending.reject') }}</button>
            <button type="button" class="brain-unit-browser__pending-apply" @click="$emit('confirm-pending')">{{ $t('common.apply') }}</button>
          </div>
        </header>
        <article v-if="port.pendingVersion.confirmed" class="brain-unit-browser__version">
          <strong>{{ $t('brain.pending.confirmedVersion') }}</strong>
          <div class="brain-unit-browser__body" v-html="renderMarkdown(formatVersion(port.pendingVersion.confirmed))"></div>
        </article>
        <article class="brain-unit-browser__version brain-unit-browser__version--pending">
          <strong>{{ $t('brain.pending.pendingVersion') }}</strong>
          <div class="brain-unit-browser__body" v-html="renderMarkdown(formatVersion(port.pendingVersion.pending))"></div>
        </article>
      </section>
      <article v-else-if="displayBody" class="brain-unit-browser__body" v-html="renderMarkdown(displayBody)"></article>
      <div v-else class="brain-unit-browser__empty">
        <span>{{ emptyText }}</span>
      </div>
    </section>
  </AppModalShell>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { UnitContentPort } from '../../types'
import type { UnitContentEffectiveVersion } from '../../types/unitContentPort'
import AppModalShell from '../common/AppModalShell.vue'
import RecallCompilePagePanel from '../recall/RecallCompilePagePanel.vue'
import { renderMarkdownToHtml } from '../../utils/markdown'

const props = defineProps<{
  open: boolean
  port: UnitContentPort | null
}>()

defineEmits<{
  (e: 'close'): void
  (e: 'confirm-pending'): void
  (e: 'reject-pending'): void
  (e: 'edit-pending'): void
}>()

const { t } = useI18n()

const compilePage = computed(() => props.port?.effectiveVersion.compilePage || null)
const displayBody = computed(() => {
  const port = props.port
  if (!port) return ''
  if (port.domain === 'characterCore' && port.contentKind !== 'group' && !port.recallableInChat && !port.hasCompilePage) return ''
  return String(port.effectiveVersion.body || port.body || port.formText || '').trim()
})
const domainLabel = computed(() => {
  switch (props.port?.domain) {
    case 'docLibrary':
      return t('brain.domainLabel.docLibrary')
    case 'characterCore':
      return t('brain.domainLabel.core')
    case 'characterSoul':
      return t('brain.domainLabel.soul')
    case 'characterTrace':
      return t('brain.domainLabel.trace')
    case 'characterArrangement':
      return t('brain.domainLabel.arrangement')
    default:
      return t('brain.domainLabel.unit')
  }
})
const emptyText = computed(() => {
  if (props.port?.contentKind === 'group') return t('brain.read.groupEmpty')
  if (props.port?.domain === 'characterCore' && !props.port.recallableInChat) return t('brain.read.systemConfigNotRecall')
  return t('brain.read.bodyEmpty')
})

function renderMarkdown(value: string) {
  return renderMarkdownToHtml(value || '')
}

function formatVersion(version: UnitContentEffectiveVersion) {
  return [
    `# ${version.title || t('brain.pending.unnamedVersion')}`,
    '',
    version.summary ? `## ${t('brain.field.summary')}\n${version.summary}` : '',
    version.body ? `## ${t('brain.field.body')}\n${version.body}` : ''
  ].filter(Boolean).join('\n\n')
}
</script>

<style scoped>
.brain-unit-browser {
  display: flex;
  flex-direction: column;
  gap: 14px;
  min-height: 0;
}

.brain-unit-browser__meta {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  color: var(--morandi-text-light, #7b746b);
  font-size: 12px;
}

.brain-unit-browser__meta span {
  min-width: 0;
  max-width: 100%;
  padding: 2px 8px;
  border: 1px solid var(--morandi-border);
  border-radius: 999px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.brain-unit-browser__body {
  min-height: 0;
  max-height: min(54vh, 520px);
  overflow: auto;
  padding: 2px 2px 12px;
  color: var(--morandi-text, #4f463f);
  line-height: 1.72;
  font-size: 14px;
}

.brain-unit-browser__versions {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
  gap: 12px;
  min-height: 0;
}

.brain-unit-browser__pending-header {
  grid-column: 1 / -1;
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 14px;
  border-top: 1px solid rgba(155, 108, 232, 0.28);
  padding-top: 10px;
}

.brain-unit-browser__pending-header > div:first-child {
  display: flex;
  min-width: 0;
  flex-direction: column;
  gap: 3px;
}

.brain-unit-browser__pending-header strong {
  color: color-mix(in srgb, var(--morandi-text, #4f463f) 82%, #9b6ce8 18%);
  font-size: 13px;
}

.brain-unit-browser__pending-header span {
  color: var(--morandi-text-light, #7b746b);
  font-size: 12px;
}

.brain-unit-browser__pending-actions {
  display: inline-flex;
  flex: 0 0 auto;
  gap: 6px;
}

.brain-unit-browser__pending-actions button {
  min-width: 48px;
  height: 26px;
  border: 1px solid var(--morandi-border);
  border-radius: 6px;
  background: color-mix(in srgb, var(--morandi-card) 82%, transparent);
  color: var(--morandi-text, #4f463f);
  font-size: 12px;
  cursor: pointer;
}

.brain-unit-browser__pending-actions button:hover {
  border-color: rgba(155, 108, 232, 0.38);
}

.brain-unit-browser__pending-apply {
  background: color-mix(in srgb, #9b6ce8 15%, var(--morandi-card)) !important;
}

.brain-unit-browser__version {
  min-width: 0;
  border-top: 1px solid var(--morandi-border);
  padding-top: 10px;
}

.brain-unit-browser__version > strong {
  display: block;
  margin-bottom: 8px;
  color: var(--morandi-text, #4f463f);
  font-size: 13px;
}

.brain-unit-browser__version--pending {
  border-top-color: rgba(190, 151, 64, 0.32);
}

@media (max-width: 720px) {
  .brain-unit-browser__versions {
    grid-template-columns: 1fr;
  }

  .brain-unit-browser__pending-header {
    flex-direction: column;
  }
}

.brain-unit-browser__body :deep(h1),
.brain-unit-browser__body :deep(h2),
.brain-unit-browser__body :deep(h3) {
  margin: 12px 0 8px;
  font-size: 1rem;
  line-height: 1.45;
}

.brain-unit-browser__body :deep(p) {
  margin: 0 0 10px;
}

.brain-unit-browser__body :deep(ul),
.brain-unit-browser__body :deep(ol) {
  margin: 0 0 10px;
  padding-left: 20px;
}

.brain-unit-browser__body :deep(pre) {
  white-space: pre-wrap;
}

.brain-unit-browser__empty {
  border-top: 1px solid var(--morandi-border);
  padding: 16px 0 4px;
  color: var(--morandi-text-light, #7b746b);
  font-size: 13px;
}
</style>
