/**
 * API 端点配置
 */

// 基础路径
const API_BASE = ''

/** API 端点集合 */
export const API = {
  // 数据接口
  AI_USAGE: `${API_BASE}/api/data/ai-usage`,
  aiUsageRound: (roundId: string) => `${API_BASE}/api/data/ai-usage/round?roundId=${encodeURIComponent(roundId)}`,
  // 星依聊天日记化归档（2026-07-16 批次3）：日记视角设置读写 + 立即生成今天日记
  XINGYI_DIARY_VIEWPOINT: `${API_BASE}/api/data/xingyi/diary/viewpoint`,
  XINGYI_DIARY_GENERATE_NOW: `${API_BASE}/api/data/xingyi/diary/generate-now`,
  XINGYI_DIARY_AUTO_GENERATE_DUE: `${API_BASE}/api/data/xingyi/diary/auto-generate-due`,
  // 星依读日记：日记归档目录/单篇只读。
  XINGYI_DIARY_FILES: `${API_BASE}/api/data/xingyi/diary/files`,
  xingyiDiaryFile: (dateStr: string) => `${API_BASE}/api/data/xingyi/diary/files/${encodeURIComponent(dateStr)}`,
  APP_CHANGELOG: `${API_BASE}/api/data/app-changelog`,
  DATA: `${API_BASE}/api/data`,
  ALL_DATA: `${API_BASE}/api/data/all`,
  CONFIG: `${API_BASE}/api/data/config`,
  ORCHESTRATOR_CONFIG: `${API_BASE}/api/data/orchestrator-config`,
  ORCHESTRATOR_CONFIG_EFFECTIVE: `${API_BASE}/api/data/orchestrator-config/effective`,
  PERSONALITY_RERANKER_SCORE: `${API_BASE}/api/data/personality-reranker/score`,
  PERSONALITY_RERANKER_PREFERENCES: `${API_BASE}/api/data/personality-reranker/preferences`,
  CHARACTERS: `${API_BASE}/api/data/characters`,
  CONTACTS_BATCH_DELETE: `${API_BASE}/api/data/contacts/batch-delete`,
  characterSnapshots: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/snapshots`,
  characterSnapshot: (characterId: string, snapshotId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/snapshots/${encodeURIComponent(snapshotId)}`,
  characterSnapshotsCleanup: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/snapshots/cleanup`,
  characterSnapshotOverwriteMain: (characterId: string, snapshotId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/snapshots/${encodeURIComponent(snapshotId)}/overwrite-main`,
  characterCompleteExport: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/export-complete`,
  characterPersonalityModel: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-model`,
  characterPersonalityModelVersions: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-model/versions`,
  characterPersonalityModelVersionInstall: (characterId: string, versionId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-model/versions/${encodeURIComponent(versionId)}/install`,
  characterPersonalityModelVersionExport: (characterId: string, versionId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-model/versions/${encodeURIComponent(versionId)}/export`,
  characterPersonalityModelVersionImport: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-model/versions/import`,
  characterPersonalityModelVersion: (characterId: string, versionId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-model/versions/${encodeURIComponent(versionId)}`,
  characterPersonalityModelVersionMetrics: (characterId: string, versionId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-model/versions/${encodeURIComponent(versionId)}/metrics`,
  characterPersonalityTrainingDatasets: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/datasets`,
  characterPersonalityTrainingDatasetQuestionnaire: (characterId: string, datasetId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/datasets/${encodeURIComponent(datasetId)}/questionnaire`,
  characterPersonalityTrainingDatasetAnswers: (characterId: string, datasetId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/datasets/${encodeURIComponent(datasetId)}/answers`,
  characterPersonalityTrainingPrecheck: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/precheck`,
  characterPersonalityTrainingRuns: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/runs`,
  characterPersonalityTrainingRun: (characterId: string, runId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/runs/${encodeURIComponent(runId)}`,
  characterPersonalityTrainingRunLog: (characterId: string, runId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/runs/${encodeURIComponent(runId)}/log`,
  characterPersonalityTrainingRunCancel: (characterId: string, runId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/runs/${encodeURIComponent(runId)}/cancel`,
  characterPersonalityTrainingRunImport: (characterId: string, runId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/runs/${encodeURIComponent(runId)}/import`,
  characterPersonalityTrainingColabPackage: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/colab-package`,
  characterPersonalityTrainingChatMessages: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/chat-messages`,
  characterPersonalityTrainingChatSampleDrafts: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/chat-sample-drafts`,
  characterPersonalityTrainingEvaluationSets: (characterId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/evaluation-sets`,
  characterPersonalityTrainingEvaluationSetAnswers: (characterId: string, evalSetId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/evaluation-sets/${encodeURIComponent(evalSetId)}/answers`,
  characterPersonalityTrainingEvaluationSetQuestions: (characterId: string, evalSetId: string) => `${API_BASE}/api/data/characters/${encodeURIComponent(characterId)}/personality-training/evaluation-sets/${encodeURIComponent(evalSetId)}/questions`,
  CHARACTER_GROUPS: `${API_BASE}/api/data/character-groups`,
  DOC_LIBRARY: `${API_BASE}/api/data/doc-library`,
  SILLYTAVERN_WORLDBOOK_PREVIEW: `${API_BASE}/api/data/doc-library/import/sillytavern-worldbook/preview`,
  SILLYTAVERN_WORLDBOOK_APPLY: `${API_BASE}/api/data/doc-library/import/sillytavern-worldbook/apply`,
  WORLD_DRAFT_IMPORT_PREVIEW: `${API_BASE}/api/data/doc-library/import/world-draft/preview`,
  WORLD_DRAFT_IMPORT_APPLY: `${API_BASE}/api/data/doc-library/import/world-draft/apply`,
  BRAIN_NEURONS: `${API_BASE}/api/data/brain-neurons`,
  GROUPS: `${API_BASE}/api/data/groups`,
  CROWDS: `${API_BASE}/api/data/crowds`,
  ALIASES: `${API_BASE}/api/data/aliases`,
  USER_PROFILE: `${API_BASE}/api/data/user-profile`,
  RESOURCES: `${API_BASE}/api/data/resources`,
  TICKETS: `${API_BASE}/api/data/tickets`,
  TICKET_CATEGORIES: `${API_BASE}/api/data/ticket-categories`,
  HISTORY: `${API_BASE}/api/data/history`,
  TASKS: `${API_BASE}/api/data/tasks`,
  TASK_LOGS: `${API_BASE}/api/data/task-logs`,
  DAILY_REPORTS: `${API_BASE}/api/data/daily-reports`,
  SUMMARIES: `${API_BASE}/api/data/summaries`,
  SMALL_SUMMARIES: `${API_BASE}/api/data/small-summaries`,
  BIG_SUMMARIES: `${API_BASE}/api/data/big-summaries`,
  API_PRESETS: `${API_BASE}/api/data/api-presets`,
  PROMPT_PRESETS: `${API_BASE}/api/data/prompt-presets`,
  LOCAL_EXPORT: `${API_BASE}/api/data/export`,
  LOCAL_RESTORE: `${API_BASE}/api/data/restore`,
  LOCAL_RESTORE_PARTITIONS: `${API_BASE}/api/data/restore/partitions`,
  SAVE_WORKSPACE: `${API_BASE}/api/data/save`,
  CHAT_BASE: `${API_BASE}/api/data/chat`,
  CHAT_IMAGES: `${API_BASE}/api/data/chat-images`,
  CHAT_SESSIONS: `${API_BASE}/api/data/chat-sessions`,
  CHAT_SESSIONS_BATCH_DELETE: `${API_BASE}/api/data/chat-sessions/batch-delete`,
  chatSessionById: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}`,
  chatSessionAgentContextResolve: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/agent-context/resolve`,
  chatSessionCharacterState: (sessionId: string, characterId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/characters/${encodeURIComponent(characterId)}/state`,
  chatSessionCharacterPresence: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/character-presence`,
  chatSessionCharacterPresenceEvents: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/character-presence/events`,
  chatSessionCharacterPresenceSet: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/character-presence/set`,
  chatSessionCharacterPresencePropose: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/character-presence/propose`,
  chatSessionCharacterPresenceCommit: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/character-presence/commit`,
  chatSessionCharacterPresenceCancel: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/character-presence/cancel`,
    chatSessionOrchestrationMaterials: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/orchestration-materials`,
    chatSessionOrchestrationWorkspace: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/orchestration-workspace`,
    chatSessionDirectorOrchestrationProjection: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/orchestration-workspace/director`,
    chatSessionOrchestrationWorkspaceCommands: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/orchestration-workspace/commands`,
    chatSessionNarrativeSeedTimeGateSync: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/narrative-seeds/sync-time-gates`,
    chatSessionPostRoundRuns: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/post-round-runs`,
    chatSessionPostRoundRun: (sessionId: string, runId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/post-round-runs/${encodeURIComponent(runId)}`,
  chatSessionNarrativeOverride: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/orchestration-materials/narrative-override`,
  chatSessionOrchestrationState: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/orchestration-materials/state`,
  chatSessionArchive: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/archive`,
  chatSessionClearContext: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/clear-context`,
  chatSessionMessages: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/messages`,
  chatSessionMessage: (sessionId: string, messageId: number) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/messages/${messageId}`,
  chatSessionMessageProjectionRun: (sessionId: string, messageId: number | string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/messages/${encodeURIComponent(String(messageId))}/projection/run`,
  chatSessionMessageProjectionEmbedded: (sessionId: string, messageId: number | string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/messages/${encodeURIComponent(String(messageId))}/projection/embedded`,
  chatSessionPersonalityModelContext: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/personality-model/context`,
  chatSessionProjectionFirstMessageView: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/projection-first-message-view`,
  chatSessionPersonalityModelObservations: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/personality-model/observations`,
  chatSessionPersonalityProjectionWritebackRun: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/personality-model/projection-writeback/run`,
  chatSessionGenerationAttempts: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/generation-attempts`,
  chatSessionGenerationAttempt: (sessionId: string, attemptId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/generation-attempts/${encodeURIComponent(attemptId)}`,
  chatSessionGenerationAttemptLatest: (sessionId: string, anchorMessageId: number) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/generation-attempts/latest?anchorMessageId=${encodeURIComponent(String(anchorMessageId || 0))}`,
  chatSessionGenerationAttemptsByRun: (sessionId: string, tidiaoRunId: string, limit = 200) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/generation-attempts/by-run?runId=${encodeURIComponent(tidiaoRunId || '')}&limit=${encodeURIComponent(String(limit || 200))}`,
  chatSessionGenerationAttemptArtifacts: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/generation-attempt-artifacts`,
  chatSessionMessageNotes: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/message-notes`,
  chatSessionMessageNote: (sessionId: string, noteId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/message-notes/${encodeURIComponent(noteId)}`,
  chatSessionImprovisedCharacterContext: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/improvised-character/context`,
  chatSessionImprovisedCharacterExtract: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/improvised-character/extract`,
  chatSessionImprovisedCharacterCreate: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/improvised-character/create`,
  chatSessionTemporaryCharacters: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/session-temporary-characters`,
  chatSessionTemporaryCharacter: (sessionId: string, characterId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/session-temporary-characters/${encodeURIComponent(characterId)}`,
  chatSessionTemporaryCharacterResolveMention: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/session-temporary-characters/resolve-mention`,
  chatSessionTemporaryEntities: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/session-temporary-entities`,
  chatSessionTemporaryEntity: (sessionId: string, entityId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/session-temporary-entities/${encodeURIComponent(entityId)}`,
  chatSessionTemporaryEntityPersist: (sessionId: string, entityId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/session-temporary-entities/${encodeURIComponent(entityId)}/persist`,
  chatSessionTemporaryEntityOrganize: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/session-temporary-entities/organize`,
  chatStatusPanelTemplates: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-panel-templates`,
  chatStatusPanelTemplate: (sessionId: string, templateId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-panel-templates/${encodeURIComponent(templateId)}`,
  chatStatusPanels: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-panels`,
  chatStatusPanel: (sessionId: string, panelId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-panels/${encodeURIComponent(panelId)}`,
  chatStatusPanelEvents: (sessionId: string, panelId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-panels/${encodeURIComponent(panelId)}/events`,
  chatStatusAssets: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-assets`,
  chatStatusAssetContent: (sessionId: string, assetId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-assets/${encodeURIComponent(assetId)}/content`,
  CHAT_STATUS_ASSET_PUBLISH_TARGETS: `${API_BASE}/api/data/chat-status-assets/publish-targets`,
  chatStatusPanelMigrationPreview: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-panels/migration-preview`,
  worlds: () => `${API_BASE}/api/data/worlds`,
  // 世界管理页（世界一等公民 P1）：改名/简介、软删、详情聚合、文档库挂载——单个世界维度的 CRUD 补全
  world: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}`,
  worldDetail: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/detail`,
  worldDocLinks: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/doc-links`,
  worldEntities: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/entities`,
  worldEntity: (worldId: string, entityId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/entities/${encodeURIComponent(entityId)}`,
  worldNarrativeSeeds: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/narrative-seeds`,
  worldNarrativeScriptConfig: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/narrative-script-config`,
  worldNarrativeSeedsRelevant: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/narrative-seeds/relevant`,
  worldNarrativeSeedsOverdueScan: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/narrative-seeds/overdue-scan`,
  worldNarrativeSeed: (worldId: string, seedId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/narrative-seeds/${encodeURIComponent(seedId)}`,
  worldNarrativeSeedImpactEvents: (worldId: string, seedId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/narrative-seeds/${encodeURIComponent(seedId)}/impact-events`,
  worldNarrativeMigrationPreview: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/narrative-migration-preview`,
  worldNarrativeMigrationExecute: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/narrative-migration-execute`,
  // 地图数据骨架（地图系统批4）：读=弹窗/绘舆共用 bundle；写=绘舆工具与手插数据（用户 UI 只读不调写端点）
  worldMap: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/map`,
  worldMapSheets: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/map/sheets`,
  worldMapFeatures: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/map/features`,
  worldMapFeature: (worldId: string, featureId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/map/features/${encodeURIComponent(featureId)}`,
  // 地图版本历史（批L）：按 run 分组的变更历史（弹窗右侧「历史」面板消费）
  worldMapChangeLog: (worldId: string) => `${API_BASE}/api/data/worlds/${encodeURIComponent(worldId)}/map/change-log`,
  chatSessionWorld: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/world`,
  chatStatusPanelsMergeIntoWorld: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/status-panels/merge-into-world`,
  chatSessionPromptLogs: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/prompt-logs`,
  chatSessionPromptLogBind: (sessionId: string, logId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/prompt-logs/${encodeURIComponent(logId)}/bind-message`,
  chatSessionPromptLogsByMessage: (sessionId: string, messageId: number, keepLogId = '') => {
    const query = keepLogId ? `?keepLogId=${encodeURIComponent(keepLogId)}` : ''
    return `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/prompt-logs/by-message/${messageId}${query}`
  },
  chatSessionPromptLogLocate: (sessionId: string, messageId: number, kind = '') => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/prompt-logs/locate/${messageId}${kind ? `?kind=${encodeURIComponent(kind)}` : ''}`,
  chatSessionPromptLogLocateByLogId: (sessionId: string, logId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/prompt-logs/locate-log/${encodeURIComponent(logId)}`,
  chatSessionRecallActivityLogs: (sessionId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/recall-activity-logs`,
  chatSessionRecallActivityLogBind: (sessionId: string, logId: string) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/recall-activity-logs/${encodeURIComponent(logId)}/bind-message`,
  chatSessionRecallActivityLogLocate: (sessionId: string, messageId: number) => `${API_BASE}/api/data/chat-sessions/${encodeURIComponent(sessionId)}/recall-activity-logs/locate/${messageId}`,
  chatSession: (targetId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}`,
  chatMessages: (targetId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/messages`,
  chatMessagesBatchCopy: (targetId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/messages/batch-copy`,
  chatMessage: (targetId: string, messageId: number) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/messages/${messageId}`,
  chatSessionPatch: (targetId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/session`,
  chatPromptLogs: (targetId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/prompt-logs`,
  chatPromptLogBind: (targetId: string, logId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/prompt-logs/${encodeURIComponent(logId)}/bind-message`,
  chatPromptLogsByMessage: (targetId: string, messageId: number, keepLogId = '') => {
    const query = keepLogId ? `?keepLogId=${encodeURIComponent(keepLogId)}` : ''
    return `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/prompt-logs/by-message/${messageId}${query}`
  },
  chatPromptLogLocate: (targetId: string, messageId: number, kind = '') => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/prompt-logs/locate/${messageId}${kind ? `?kind=${encodeURIComponent(kind)}` : ''}`,
  chatPromptLogLocateByLogId: (targetId: string, logId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/prompt-logs/locate-log/${encodeURIComponent(logId)}`,
  chatRecallActivityLogs: (targetId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/recall-activity-logs`,
  chatRecallActivityLogBind: (targetId: string, logId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/recall-activity-logs/${encodeURIComponent(logId)}/bind-message`,
  chatRecallActivityLogLocate: (targetId: string, messageId: number) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/recall-activity-logs/locate/${messageId}`,
  chatArchives: `${API_BASE}/api/data/chat-archives`,
  chatArchive: (archiveId: string) => `${API_BASE}/api/data/chat-archives/${encodeURIComponent(archiveId)}`,
  chatArchiveLoad: (archiveId: string, targetId: string) => `${API_BASE}/api/data/chat-archives/${encodeURIComponent(archiveId)}/load/${encodeURIComponent(targetId)}`,
  chatArchiveExport: `${API_BASE}/api/data/chat-archives/export`,
  chatArchiveImport: `${API_BASE}/api/data/chat-archives/import`,
  chatArchiveNewChat: (targetId: string) => `${API_BASE}/api/data/chat/${encodeURIComponent(targetId)}/new-session`,

  // AI 接口
  AI: `${API_BASE}/api/ai`,
  AI_CHAT: `${API_BASE}/api/ai/chat`,
  AI_IMAGE_GENERATION: `${API_BASE}/api/ai/images/generate`,
  AI_WEB_SEARCH: `${API_BASE}/api/ai/web/search`,
  AI_MODELS: `${API_BASE}/api/ai/models`,
  AI_EMBEDDINGS: `${API_BASE}/api/ai/embeddings`,

  // 计时器接口
  TIMERS: `${API_BASE}/api/timers`,

  // 自定义标签接口
  CUSTOM_TAGS: `${API_BASE}/api/data/custom-tags`,

  // 事栈接口
  EVENT_STACK: `${API_BASE}/api/data/event-stack`,
  EVENT_STACK_TODAY: `${API_BASE}/api/data/event-stack/today`,

  // 天气接口
  WEATHER: `${API_BASE}/api/weather`,
  WEATHER_NOW: `${API_BASE}/api/weather/now`,
  WEATHER_CITY: `${API_BASE}/api/weather/city`,
  WEATHER_GEO: `${API_BASE}/api/weather/geo`,
  WEATHER_CONFIG: `${API_BASE}/api/weather/config`
} as const
