import { describe, expect, it, vi } from 'vitest'
import { buildWorkspaceShellControllerRuntimeState } from '../../../src/composables/app/useWorkspaceShellControllerRuntimeState.ts'

describe('useWorkspaceShellControllerRuntimeState', () => {
  it('会返回视图桥需要的运行态集合', () => {
    // 与 buildWorkspaceShellControllerRuntimeState 的返回键集严格对齐（toEqual 是穷举快照）。
    // 多批次（5b 纠偏 / M1b / M2 / M3 精修 等）陆续给运行态补键，本 mock 同步到当前真值。
    const state = {
      streamingText: '',
      currentStreamingSpeakerName: '',
      currentStreamingTargetId: '',
      environmentNarrationLoading: false,
      plannedGroupSpeakers: [],
      editingMessageIndex: -1,
      editingMessageContent: '',
      regeneratingMessageIndex: -1,
      mentionSelectedChars: [],
      mentionExcludedChars: [],
      runtimeTransactions: [],
      transactionExecuting: false,
      hasTaskTimeline: false,
      getTaskTimelineNodes: vi.fn(),
      isRequestingTask: false,
      expandedTaskId: '',
      customMarkType: '',
      customMarkNote: '',
      newTaskName: '',
      newTaskDesc: '',
      newTaskReward: '',
      newTaskCategory: '',
      newTaskBonus: '',
      taskAssignerChar: '',
      taskLoadContact: '',
      newCharForm: null,
      charGroupEditForm: null,
      editingGroupId: '',
      groupForm: null,
      groupEditForm: null,
      showGroupEditor: false,
      sceneForm: null,
      editingCrowdId: '',
      crowdForm: null,
      showAddCharacter: false,
      showCharGroupManager: false,
      showCreateGroup: false,
      showCrowdEditor: false,
      showChatSummary: false,
      showConversationManager: false,
      showPromptPresetEditor: false,
      showUserEditor: false,
      showSpendMoney: false,
      clearCurrentChat: vi.fn(),
      requestClearCurrentChatContext: vi.fn(),
      addMentionChar: vi.fn(),
      removeMentionChar: vi.fn(),
      toggleExcludeChar: vi.fn(),
      togglePlusMenu: vi.fn(),
      startEditMessage: vi.fn(),
      cancelEditMessage: vi.fn(),
      saveEditMessage: vi.fn(),
      saveAndRegenerate: vi.fn(),
      updateCorrectionText: vi.fn(),
      continueCorrection: vi.fn(),
      cancelCorrection: vi.fn(),
      deleteMessage: vi.fn(),
      selectMessageVersion: vi.fn(),
      copyMessage: vi.fn(),
      toggleMessagePromptVisibility: vi.fn(),
      regenerateMsg: vi.fn(),
      applyDirectorPrecisionEdits: vi.fn(),
      sidebarOpen: false,
      collapsedGroups: {},
      editCharacter: vi.fn(),
      showCharacterEditor: false,
      showCurtainPanel: false,
      showAliasSelector: false,
      setMessagesAreaRef: vi.fn(),
      plusMenuOpen: false,
      atMenuOpen: false,
      chatInputText: '',
      onInputChatText: vi.fn(),
      setMenuContainerRef: vi.fn(),
      setChatInputRef: vi.fn(),
      operationDetail: null
    }

    const result = buildWorkspaceShellControllerRuntimeState(state)

    expect(result).toEqual(state)
  })
})
