import { describe, expect, it, vi, beforeEach } from 'vitest'
import { computed } from 'vue'

const useWorkspaceShellControllerBootMock = vi.fn()
const useWorkspaceShellControllerDomainsMock = vi.fn()
const useAppShellOpsHubMock = vi.fn()
const useAppShellFlowHubMock = vi.fn()
const useAppShellViewBridgeMock = vi.fn()
const buildAppShellOpsHubContextMock = vi.fn((ctx) => ctx)
const buildAppShellControllerFlowHubContextMock = vi.fn((ctx) => ctx)
const buildAppShellControllerViewBridgeContextMock = vi.fn((ctx) => ctx)
const buildAppShellControllerReturnMock = vi.fn((ctx) => ctx)

vi.mock('../../../src/composables/app/useWorkspaceShellControllerBoot.ts', () => ({
  useWorkspaceShellControllerBoot: useWorkspaceShellControllerBootMock
}))
vi.mock('../../../src/composables/app/useWorkspaceShellControllerDomains.ts', () => ({
  useWorkspaceShellControllerDomains: useWorkspaceShellControllerDomainsMock
}))
vi.mock('../../../src/composables/app/useAppShellOpsHub.ts', () => ({
  useAppShellOpsHub: useAppShellOpsHubMock
}))
vi.mock('../../../src/composables/app/useAppShellFlowHub.ts', () => ({
  useAppShellFlowHub: useAppShellFlowHubMock
}))
vi.mock('../../../src/composables/app/useAppShellViewBridge.ts', () => ({
  useAppShellViewBridge: useAppShellViewBridgeMock
}))
vi.mock('../../../src/composables/app/useAppShellAssemblers.ts', () => ({
  buildAppShellOpsHubContext: buildAppShellOpsHubContextMock,
  buildAppShellControllerFlowHubContext: buildAppShellControllerFlowHubContextMock,
  buildAppShellControllerViewBridgeContext: buildAppShellControllerViewBridgeContextMock,
  buildAppShellControllerReturn: buildAppShellControllerReturnMock
}))

describe('useWorkspaceShellController', () => {
  beforeEach(() => {
    vi.resetAllMocks()
  })

  it('会复用 boot helper 提供的壳层基础依赖', async () => {
    const callAI = vi.fn()
    const callAIStream = vi.fn()
    useWorkspaceShellControllerBootMock.mockReturnValue({
      resourceStore: {},
      charStore: {},
      chatStore: { current: {}, activeChatTargetId: 'char_1' },
      settingStore: {},
      taskStore: {},
      callAI,
      callAIStream,
      cleanAiPrefix: vi.fn(),
      detectLocationChange: vi.fn(),
      buildSystemPrompt: vi.fn(),
      buildPromptMessages: vi.fn(),
      timerComposable: {},
      cloudSync: {},
      toastVisible: false,
      toastMessage: '',
      toastType: 'info',
      toast: vi.fn(),
      appState: {
        showAddTicket: false,
        showEditTicket: false,
        showSpendMoney: false,
        showBatchExchange: false,
        showBatchUse: false,
        showCategoryEditor: false,
        categoryEditList: [],
        newCategoryName: '',
        showConfirmDialog: {},
        confirmDialog: {},
        showChatTransferDialog: {},
        chatTransferDialog: {},
        showAddPointsModal: false,
        showSettingModal: false,
        showUserEditor: false,
        showAddCharacter: false,
        showCharacterEditor: false,
        showCurtainPanel: false,
        showSceneEditor: false,
        showAliasEditor: false,
        showAliasSelector: false,
        showTTSConfig: false,
        showAffectionConfig: false,
        showCharGroupManager: false,
        showCrowdEditor: false,
        showCreateGroup: false,
        showGroupEditor: false,
        showAddApiPreset: false,
        isLoadingModels: false,
        isTestingApi: false,
        currentApiPresetIndex: 0,
        autoSyncTime: false,
        modelList: [],
        showEditApiPreset: false,
        showPromptPresetEditor: false,
        showPresetVars: false,
        presetSceneFilter: '',
        showLocationEdit: false,
        showWeatherEdit: false,
        fullscreenImage: '',
        charEditorTab: '',
        ticketForm: {},
        editingTicketId: '',
        spendAmount: 0,
        spendReason: '',
        batchTicket: '',
        batchAmount: 0,
        autoConsumeEnabled: false,
        addPointsAmount: 0,
        userForm: {},
        newCharForm: {},
        charEditForm: {},
        showDetailSettings: false,
        showScheduleEditor: false,
        showRelationshipEditor: false,
        showYearlyScheduleEditor: false,
        showActivitiesEditor: false,
        showLocationsEditor: false,
        collapsedDays: {},
        showCopySlotDialog: false,
        copyingFromDay: '',
        copyingSlot: '',
        copyTargetDays: [],
        newRelationshipTarget: '',
        newNicknameInput: '',
        newActivityInput: '',
        newLocationInput: '',
        affectionLocked: false,
        weekDays: [],
        timeOptions: [],
        sceneForm: {},
        aliasForm: {},
        editingAliasId: '',
        crowdForm: {},
        editingCrowdId: '',
        groupForm: {},
        editingGroupId: '',
        groupEditForm: {},
        apiPresetForm: {},
        promptPresetForm: {},
        editingPresetIndex: 0,
        newGroupName: '',
        newGroupEmoji: '',
        isLoadingLocation: false,
        isLoadingWeather: false,
        showWeatherDetail: false,
        editingLocation: false,
        tempLocation: '',
        weatherApiKey: '',
        weatherApiDomain: '',
        currentTicketCategory: '',
        cloudEmail: '',
        cloudPassword: '',
        cloudLoggedIn: false,
        cloudUsername: '',
        newTaskName: '',
        newTaskReward: 0,
        newTaskDesc: '',
        newTaskCategory: '',
        newTaskBonus: 0,
        taskAssignerChar: '',
        taskLoadContact: '',
        isRequestingTask: false,
        currentTaskTab: '',
        expandedTaskId: '',
        operationDetail: '',
        customMarkType: '',
        customMarkNote: '',
        taskTimerUpdateInterval: 0,
        customTags: [],
        showTagManager: false,
        newTagName: '',
        newTagColor: '',
        editingTagId: '',
        eventStack: [],
        eventStackSummary: [],
        tagColorPresets: [],
        messagesArea: null,
        importFileInput: null,
        setMessagesAreaRef: vi.fn()
      },
      chatUiState: {
        chatInputText: '',
        plusMenuOpen: false,
        atMenuOpen: false,
        atSearchText: '',
        mentionSelectedChars: [],
        mentionExcludedChars: [],
        handleClickOutside: vi.fn(),
        togglePlusMenu: vi.fn(),
        insertAtCharacter: vi.fn(),
        getCharNameById: vi.fn(),
        addMentionChar: vi.fn(),
        removeMentionChar: vi.fn(),
        toggleExcludeChar: vi.fn(),
        insertOOC: vi.fn(),
        insertNarration: vi.fn(),
        insertSystemMsg: vi.fn(),
        clearCurrentChat: vi.fn(),
        setMenuContainerRef: vi.fn(),
        setChatInputRef: vi.fn(),
        onInputChatText: vi.fn()
      },
      shellSupport: {
        sidebarOpen: false,
        collapsedGroups: {},
        sections: [],
        streamingText: '',
        currentStreamingSpeakerName: '',
        currentStreamingTargetId: '',
        transactionExecuting: false,
        editingCharacter: null,
        editCharacter: vi.fn(),
        resetEditingCharacter: vi.fn(),
        loadedSummaryItems: []
      },
      workspaceRuntime: {
        workspaceKernel: {},
        workspaceCommandRegistry: {
          registerCommand: vi.fn(),
          executeCommand: vi.fn(async () => true)
        },
        workspaceBootSession: {},
        workspaceRuntimeStore: {},
        isBootLoading: false,
        runtimeTransactions: [],
        cloudActionState: {},
        workspaceLoadingStage: '',
        workspaceLoadingMessage: ''
      },
      uiHelpers: {
        timerCompleteVisible: false,
        timerCompleteTicketName: '',
        timerCompleteMessage: '',
        timerCompleteTitle: '',
        timerCompleteType: 'info',
        closeTimerCompleteModal: vi.fn(),
        formatChatText: vi.fn(),
        abortChat: vi.fn(),
        toggleGroupCollapse: vi.fn(),
        getCharactersByGroup: vi.fn(),
        handleConfirmClick: vi.fn(),
        openConfirmDialog: vi.fn(),
        closeChatTransferDialog: vi.fn(),
        confirmChatTransfer: vi.fn()
      },
      taskTimelineHelpers: {
        getTaskTimelineDuration: vi.fn(),
        hasTaskTimeline: vi.fn(),
        getTaskTimelineNodes: vi.fn()
      },
      appSmallHelpers: {
        normalizeAvatarUrl: vi.fn(),
        getTemperatureFromWeather: vi.fn()
      },
      environmentOps: {
        getWeatherText: vi.fn(),
        loadWeatherConfig: vi.fn(),
        saveWeatherApiConfig: vi.fn(),
        editLocation: vi.fn(),
        saveLocation: vi.fn(),
        cancelLocationEdit: vi.fn(),
        syncWeather: vi.fn(),
        autoGetLocation: vi.fn(),
        updateCurrentTime: vi.fn(),
        updateCurrentTimeSilent: vi.fn(),
        fetchWeather: vi.fn()
      }
    })
    useWorkspaceShellControllerDomainsMock.mockReturnValue({
      chatTargetHelpers: {
      getTargetName: vi.fn(),
      getCharEmoji: vi.fn(),
      getCharAvatar: vi.fn(),
      getCharAvatarById: vi.fn(),
      openCharSettingsByName: vi.fn(),
      scrollToBottom: vi.fn(),
      switchChat: vi.fn()
      },
      derivedState: {
        currentChatTitle: computed(() => ''),
        currentCharacter: computed(() => null),
        currentCharacterAvatar: computed(() => ''),
        currentMessages: computed(() => []),
        currentScene: computed(() => null),
        currentBoundAlias: computed(() => null),
        currentAlias: computed(() => null),
        loadedSummaryCount: computed(() => 0),
        ungroupedCharacters: computed(() => []),
        allTicketCategories: computed(() => []),
        filteredTickets: computed(() => []),
        filteredAtCharacters: computed(() => []),
        filteredTasks: computed(() => []),
        pendingTasks: computed(() => []),
        mobileTasks: computed(() => []),
        taskPanelMeta: computed(() => ({})),
        chatPanelViewModel: computed(() => ({})),
        settingsPanelViewModel: computed(() => ({}))
      },
      editorCharacter: computed(() => null),
      chatTransfer: { transferCurrentChat: vi.fn() },
      characterManagement: {
      addNewCharacter: vi.fn(),
      addScheduleSlot: vi.fn(),
      removeScheduleSlot: vi.fn(),
      toggleDayCollapse: vi.fn(),
      openCopySlotDialog: vi.fn(),
      confirmCopySlot: vi.fn(),
      addRelationship: vi.fn(),
      removeRelationship: vi.fn(),
      getAvailableRelationTargets: vi.fn(),
      getAffectionDesc: vi.fn(),
      addYearlyEntry: vi.fn(),
      removeYearlyEntry: vi.fn(),
      addNickname: vi.fn(),
      removeNickname: vi.fn(),
      addActivity: vi.fn(),
      removeActivity: vi.fn(),
      addLocation: vi.fn(),
      removeLocation: vi.fn(),
      handleNewCharacterAvatarUpload: vi.fn(),
      importCharacterJson: vi.fn(),
      exportCharacterJsonTemplate: vi.fn(),
      exportCurrentCharacterJson: vi.fn(),
      handleAvatarUpload: vi.fn(),
      saveCharacterEdit: vi.fn(),
      deleteCurrentCharacter: vi.fn(),
      openCurtainPanel: vi.fn(),
      openSceneEditor: vi.fn(),
      saveScene: vi.fn(),
      clearScene: vi.fn(),
      bindAlias: vi.fn(),
      saveAlias: vi.fn(),
      deleteAlias: vi.fn(),
      addNewCharGroup: vi.fn(),
      editCharGroup: vi.fn(),
      saveGroup: vi.fn(),
      deleteGroup: vi.fn(),
      editGroup: vi.fn(),
      saveGroupEdit: vi.fn(),
      editCrowd: vi.fn(),
      saveCrowd: vi.fn(),
      deleteCrowd: vi.fn()
      },
      apiPresetManager: {
        editApiPreset: vi.fn(),
        loadApiPreset: vi.fn(),
        addNewApiPreset: vi.fn(),
        loadModels: vi.fn(),
        testApiConnection: vi.fn(),
        saveApiPreset: vi.fn()
      }
    })
    useAppShellOpsHubMock.mockReturnValue({
      cloudModuleDefinitions: [],
      cloudSaves: [],
      selectedCloudSlot: '',
      selectedSyncModules: [],
      setSelectedSyncModules: vi.fn(),
      loadCloudSaves: vi.fn(),
      selectCloudSave: vi.fn(),
      cloudLogin: vi.fn(),
      cloudRegister: vi.fn(),
      cloudUpload: vi.fn(),
      cloudDownload: vi.fn(),
      createCloudSave: vi.fn(),
      updateCloudSaveNote: vi.fn(),
      renameCloudSave: vi.fn(),
      deleteCloudSave: vi.fn(),
      exportAllData: vi.fn(),
      importAllData: vi.fn(),
      resetAllData: vi.fn(),
      loadCustomTags: vi.fn(),
      saveCustomTag: vi.fn(),
      deleteCustomTag: vi.fn(),
      editCustomTag: vi.fn(),
      loadEventStack: vi.fn(),
      addToEventStack: vi.fn(),
      addResourceEventToStack: vi.fn(),
      exchangeTicket: vi.fn(),
      useTicket: vi.fn(),
      openEditTicket: vi.fn(),
      saveTicket: vi.fn(),
      deleteEditingTicket: vi.fn(),
      confirmSpendMoney: vi.fn(),
      executeBatchExchange: vi.fn(),
      executeBatchUse: vi.fn(),
      executeAddBigTime: vi.fn(),
      executeAddSmallTime: vi.fn(),
      executeConvertToPoints: vi.fn(),
      getGoldTicketCount: vi.fn(),
      addCategory: vi.fn(),
      saveCategories: vi.fn(),
      openCategoryEditor: vi.fn(),
      addCustomTask: vi.fn(),
      submitTask: vi.fn(),
      editTask: vi.fn(),
      deleteTask: vi.fn(),
      startTaskTimer: vi.fn(),
      stopTaskTimerUpdate: vi.fn(),
      pauseTaskTimer: vi.fn(),
      resetTaskTimer: vi.fn(),
      addTaskMark: vi.fn(),
      useCustomTag: vi.fn(),
      failTaskConfirm: vi.fn(),
      filteredPresets: [],
      saveUserProfile: vi.fn(),
      handleUserSave: vi.fn(),
      getOriginalIndex: vi.fn(),
      resetPresetToDefault: vi.fn(),
      editPromptPreset: vi.fn(),
      addPromptPreset: vi.fn(),
      savePromptPresetEdit: vi.fn(),
      togglePromptPresetEnabled: vi.fn(),
      dragPresetStart: vi.fn(),
      dragPresetDrop: vi.fn()
    })
    useAppShellFlowHubMock.mockReturnValue({
      utilityModalState: {},
      settingsModalState: {},
      roleModalState: {},
      characterEditorModalState: {},
      promptPresetModalState: {},
      fullscreenModalState: {},
      editingMessageIndex: -1,
      editingMessageContent: '',
      regeneratingMessageIndex: -1,
      buildChatMessages: vi.fn(),
      getAIOptions: vi.fn(),
      getDisplayedMessageContent: vi.fn(),
      selectMessageVersion: vi.fn(),
      copyMessage: vi.fn(),
      regenerateMsg: vi.fn(),
      startEditMessage: vi.fn(),
      saveEditMessage: vi.fn(),
      cancelEditMessage: vi.fn(),
      saveAndRegenerate: vi.fn(),
      deleteMessage: vi.fn(),
      showConversationManager: false,
      showChatSummary: false,
      showSummaryList: false,
      showSummaryEditor: false,
      showBigSummaryConfirm: false,
      showSlotManager: false,
      summaryContent: '',
      summaryEditForm: {},
      allChatTargets: [],
      isSummaryLoaded: vi.fn(),
      toggleSummarySlot: vi.fn(),
      saveSummaryToLibrary: vi.fn(),
      editSummaryItem: vi.fn(),
      saveSummaryEdit: vi.fn(),
      generateSummary: vi.fn(),
      confirmBigSummary: vi.fn(),
      chatManageModalState: {},
      sendChat: vi.fn(),
      runGroupChat: vi.fn(),
      stageTransaction: vi.fn(),
      removeTransactionAt: vi.fn(),
      clearTransactions: vi.fn(),
      confirmTransactions: vi.fn(),
      addTransaction: vi.fn(),
      completeTaskWithPause: vi.fn(),
      queueTaskFailure: vi.fn(),
      confirmTransactionAt: vi.fn(),
      dispatchAITask: vi.fn(),
      loadDailyReports: vi.fn(),
      getAIOptionsForTickets: vi.fn(() => ({ presetName: '', model: '' }))
    })
    useAppShellViewBridgeMock.mockReturnValue({
      commandSendChat: vi.fn(),
      commandAddTransaction: vi.fn(),
      commandClearTransactions: vi.fn(),
      commandConfirmTransactions: vi.fn(),
      commandConfirmTransactionAt: vi.fn(),
      commandRemoveTransactionAt: vi.fn(),
      commandDispatchAiTask: vi.fn(),
      commandAddCustomTask: vi.fn(),
      commandStartTaskTimer: vi.fn(),
      commandPauseTaskTimer: vi.fn(),
      commandResetTaskTimer: vi.fn(),
      commandAddTaskMark: vi.fn(),
      commandCompleteTaskWithPause: vi.fn(),
      commandQueueTaskFailure: vi.fn(),
      commandDeleteTask: vi.fn(),
      commandCloudUpload: vi.fn(),
      commandCloudDownload: vi.fn(),
      commandCreateCloudSave: vi.fn(),
      commandUpdateCloudSaveNote: vi.fn(),
      commandRenameCloudSave: vi.fn(),
      commandDeleteCloudSave: vi.fn(),
      commandSaveApiPreset: vi.fn(),
      commandSaveWeatherApiConfig: vi.fn(),
      commandResetAllData: vi.fn(),
      commandImportAllData: vi.fn(),
      cloudLogout: vi.fn(),
      desktopState: {}
    })

    const { useWorkspaceShellController } = await import('../../../src/composables/app/useWorkspaceShellController.ts')
    useWorkspaceShellController()

    expect(useWorkspaceShellControllerBootMock).toHaveBeenCalledTimes(1)
    expect(useWorkspaceShellControllerDomainsMock).toHaveBeenCalledTimes(1)
    expect(buildAppShellControllerViewBridgeContextMock).toHaveBeenCalledWith(expect.objectContaining({
      callAI,
      callAIStream
    }))
    expect(buildAppShellControllerReturnMock).toHaveBeenCalledTimes(1)
  })
})
