export function buildWorkspaceShellControllerFlowDomainBindings(ctx: any) {
  const { boot, domains, opsHub, transactionFacade, currentTargetId } = ctx
  const {
    resourceStore,
    charStore,
    chatStore,
    settingStore,
    settingEnvironmentService,
    taskStore,
    timerComposable,
    localArchiveSync,
    toast,
    workspaceRuntime,
    uiHelpers,
    appSmallHelpers,
    environmentOps
  } = boot
  const {
    chatTargetHelpers,
    derivedState,
    editorCharacter,
    characterManagement,
    apiPresetManager
  } = domains

  return {
    appState: boot.appState,
    timerComposable,
    resourceStore,
    settingStore,
    charStore,
    chatStore,
    taskStore,
    localArchiveSync,
    workspaceKernel: workspaceRuntime.workspaceKernel,
    workspaceBootSession: workspaceRuntime.workspaceBootSession,
    workspaceRuntimeStore: workspaceRuntime.workspaceRuntimeStore,
    toast,
    stopTaskTimerUpdate: opsHub.stopTaskTimerUpdate,
    loadLocalArchiveSaves: opsHub.loadLocalArchiveSaves,
    loadApiPreset: apiPresetManager.loadApiPreset,
    loadCustomTags: opsHub.loadCustomTags,
    loadEventStack: opsHub.loadEventStack,
    currentTargetId,
    editorCharacter,
    saveTicket: opsHub.saveTicket,
    deleteEditingTicket: opsHub.deleteEditingTicket,
    addCategory: opsHub.addCategory,
    saveCategories: opsHub.saveCategories,
    editCustomTag: opsHub.editCustomTag,
    deleteCustomTag: opsHub.deleteCustomTag,
    saveCustomTag: opsHub.saveCustomTag,
    addTransaction: transactionFacade.addTransaction,
    editCharGroup: characterManagement.editCharGroup,
    addNewCharGroup: characterManagement.addNewCharGroup,
    saveCrowd: characterManagement.saveCrowd,
    deleteCrowd: characterManagement.deleteCrowd,
    openCurtainPanel: characterManagement.openCurtainPanel,
    openPromptLogPanel: characterManagement.openPromptLogPanel,
    openSceneEditor: characterManagement.openSceneEditor,
    clearScene: characterManagement.clearScene,
    saveScene: characterManagement.saveScene,
    saveSessionSceneDraft: characterManagement.saveSessionSceneDraft,
    deleteAlias: characterManagement.deleteAlias,
    openAliasEditor: characterManagement.openAliasEditor,
    saveAlias: characterManagement.saveAlias,
    bindAlias: characterManagement.bindAlias,
    saveGroup: characterManagement.saveGroup,
    deleteGroup: characterManagement.deleteGroup,
    saveGroupEdit: characterManagement.saveGroupEdit,
    addNewCharacter: characterManagement.addNewCharacter,
    handleNewCharacterAvatarUpload: characterManagement.handleNewCharacterAvatarUpload,
    importCharacterJson: characterManagement.importCharacterJson,
    exportCharacterJsonTemplate: characterManagement.exportCharacterJsonTemplate,
    exportCurrentCharacterJson: characterManagement.exportCurrentCharacterJson,
    handleAvatarUpload: characterManagement.handleAvatarUpload,
    getAffectionDesc: characterManagement.getAffectionDesc,
    removeNickname: characterManagement.removeNickname,
    addNickname: characterManagement.addNickname,
    toggleDayCollapse: characterManagement.toggleDayCollapse,
    openCopySlotDialog: characterManagement.openCopySlotDialog,
    removeScheduleSlot: characterManagement.removeScheduleSlot,
    addScheduleSlot: characterManagement.addScheduleSlot,
    confirmCopySlot: characterManagement.confirmCopySlot,
    removeRelationship: characterManagement.removeRelationship,
    getAvailableRelationTargets: characterManagement.getAvailableRelationTargets,
    addRelationship: characterManagement.addRelationship,
    removeYearlyEntry: characterManagement.removeYearlyEntry,
    addYearlyEntry: characterManagement.addYearlyEntry,
    removeActivity: characterManagement.removeActivity,
    addActivity: characterManagement.addActivity,
    removeLocation: characterManagement.removeLocation,
    addLocation: characterManagement.addLocation,
    deleteCurrentCharacter: characterManagement.deleteCurrentCharacter,
    saveCharacterEdit: characterManagement.saveCharacterEdit,
    savePromptPresetEdit: opsHub.savePromptPresetEdit,
    handleConfirmClick: uiHelpers.handleConfirmClick,
    openConfirmDialog: uiHelpers.openConfirmDialog,
    handlePromptSubmit: uiHelpers.handlePromptSubmit,
    openPromptDialog: uiHelpers.openPromptDialog,
    closePromptDialog: uiHelpers.closePromptDialog,
    getCharactersByGroup: uiHelpers.getCharactersByGroup,
    settingEnvironmentService,
    updateCurrentTimeSilent: environmentOps.updateCurrentTimeSilent,
    loadWeatherConfig: environmentOps.loadWeatherConfig,
    normalizeAvatarUrl: appSmallHelpers.normalizeAvatarUrl,
    switchChat: chatTargetHelpers.switchChat,
    getTargetName: chatTargetHelpers.getTargetName,
    scrollToBottom: chatTargetHelpers.scrollToBottom,
    currentBoundAlias: derivedState.currentBoundAlias,
    currentScene: derivedState.currentScene,
    currentAlias: derivedState.currentAlias,
    currentMessages: derivedState.currentMessages
  }
}
