export function buildWorkspaceShellControllerFlowRuntimeBindings(ctx: any) {
  const { boot, opsHub } = ctx
  const {
    appState,
    chatUiState,
    shellSupport,
    callAI,
    callAIWithTools,
    callAIStream,
    cleanAiPrefix,
    detectLocationChange,
    buildSystemPrompt,
    buildPromptMessages,
    prepareAIRecall,
    buildTidiaoRetrievalContext,
    fillRoundRecallPools
  } = boot

  return {
    showCharacterEditor: appState.showCharacterEditor,
    editCharacter: shellSupport.editCharacter,
    charEditForm: appState.charEditForm,
    showDetailSettings: appState.showDetailSettings,
    showScheduleEditor: appState.showScheduleEditor,
    showRelationshipEditor: appState.showRelationshipEditor,
    showYearlyScheduleEditor: appState.showYearlyScheduleEditor,
    showActivitiesEditor: appState.showActivitiesEditor,
    showLocationsEditor: appState.showLocationsEditor,
    affectionLocked: appState.affectionLocked,
    showUserEditor: appState.showUserEditor,
    userForm: appState.userForm,
    handleClickOutside: chatUiState.handleClickOutside,
    autoSyncTime: appState.autoSyncTime,
    apiPresetForm: appState.apiPresetForm,
    currentApiPresetIndex: appState.currentApiPresetIndex,
    resetEditingCharacter: shellSupport.resetEditingCharacter,
    transactionExecuting: shellSupport.transactionExecuting,
    streamingText: shellSupport.streamingText,
    currentStreamingSpeakerName: shellSupport.currentStreamingSpeakerName,
    currentStreamingTargetId: shellSupport.currentStreamingTargetId,
    environmentNarrationLoading: shellSupport.environmentNarrationLoading,
    plannedGroupSpeakers: shellSupport.plannedGroupSpeakers,
    chatInputText: chatUiState.chatInputText,
    plusMenuOpen: chatUiState.plusMenuOpen,
    atMenuOpen: chatUiState.atMenuOpen,
    mentionSelectedChars: chatUiState.mentionSelectedChars,
    mentionExcludedChars: chatUiState.mentionExcludedChars,
    // 图片附件（批4）：发送管线专用，sendText 消费时 await 取走并清空（与 chatInputText 同源同层）。
    takeImageAttachments: chatUiState.takeImageAttachments,
    submitTask: opsHub.submitTask,
    failTaskConfirm: opsHub.failTaskConfirm,
    taskAssignerChar: appState.taskAssignerChar,
    taskLoadContact: appState.taskLoadContact,
    isRequestingTask: appState.isRequestingTask,
    callAI,
    callAIWithTools,
    callAIStream,
    cleanAiPrefix,
    detectLocationChange,
    buildSystemPrompt,
    buildPromptMessages,
    prepareAIRecall,
    buildTidiaoRetrievalContext,
    fillRoundRecallPools,
    addResourceEventToStack: opsHub.addResourceEventToStack,
    getWeatherEmoji: opsHub.getWeatherEmoji
  }
}
