export function createRoleModalState({
  appState,
  stores,
  characterOps,
  derived,
  getWeatherEmoji
}: any) {
  return {
    showCrowdEditor: appState.showCrowdEditor,
    editingCrowdId: appState.editingCrowdId,
    crowdForm: appState.crowdForm,
    viewModel: {
      get apiPresets() { return stores.settingStore.apiPresets },
      currentScene: derived.currentScene,
      currentAlias: derived.currentAlias,
      currentBoundAlias: derived.currentBoundAlias,
      get currentSession() { return stores.chatStore?.getCurrentSession?.() ?? stores.chatStore?.currentSession ?? null },
      get aliases() { return stores.charStore.aliases },
      get userProfile() { return stores.charStore.userProfile },
      currentTargetId: derived.currentTargetId,
      get characters() { return stores.charStore.characters }
    },
    saveCrowd: characterOps.saveCrowd,
    deleteCrowd: characterOps.deleteCrowd,
    showCurtainPanel: appState.showCurtainPanel,
    curtainFocusMessageId: appState.curtainFocusMessageId,
    showPromptLogPanel: appState.showPromptLogPanel,
    promptLogFocusMessageId: appState.promptLogFocusMessageId,
    showSceneEditor: appState.showSceneEditor,
    sceneForm: appState.sceneForm,
    getWeatherEmoji,
    openCurtainPanel: characterOps.openCurtainPanel,
    openPromptLogPanel: characterOps.openPromptLogPanel,
    openSceneEditor: characterOps.openSceneEditor,
    clearScene: characterOps.clearScene,
    saveScene: characterOps.saveScene,
    saveSessionSceneDraft: characterOps.saveSessionSceneDraft,
    saveSessionNarrationDraft: characterOps.saveSessionNarrationDraft,
    saveSessionDisplayDraft: characterOps.saveSessionDisplayDraft,
    showAliasEditor: appState.showAliasEditor,
    editingAliasId: appState.editingAliasId,
    aliasForm: appState.aliasForm,
    deleteAlias: characterOps.deleteAlias,
    openAliasEditor: characterOps.openAliasEditor,
    saveAlias: characterOps.saveAlias,
    showAliasSelector: appState.showAliasSelector,
    bindAlias: characterOps.bindAlias,
    showCreateGroup: appState.showCreateGroup,
    editingGroupId: appState.editingGroupId,
    groupForm: appState.groupForm,
    saveGroup: characterOps.saveGroup,
    deleteGroup: characterOps.deleteGroup,
    showGroupEditor: appState.showGroupEditor,
    groupEditForm: appState.groupEditForm,
    saveGroupEdit: characterOps.saveGroupEdit,
    assignImageAvatar: characterOps.assignImageAvatar,
    toast: characterOps.toast,
    openChatSessionCreator: characterOps.openChatSessionCreator,
    editCharacter: characterOps.editCharacter,
    showCharacterEditor: appState.showCharacterEditor,
    get characterGroups() { return stores.charStore.characterGroups }
  }
}
